
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.03-py3
    gpus: "all"
    container_name: triton
    ports:
      - "8000:8000"   # HTTP/REST
      - "8001:8001"   # gRPC
      - "8002:8002"   # Metrics & health
    volumes:
      - "C:/Vkev/Repos/Mamba-Environment/Palm-Print-Identification-System-V2/model_repository:/models:ro"
    command: >
      tritonserver
      --model-repository=/models
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    restart: always
    gpus: "all" 
    container_name: qdrant
    environment:
      - QDRANT__GPU__INDEXING=1
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO

  
